apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}
  labels:
    appname: {{ .Release.Name }}
spec: 
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      appname: {{.Release.Name}}
  template: 
    metadata:
      labels:
        appname: {{.Release.Name}}
    spec: 
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
spec: 
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
  selector:
    appname: {{.Release.Name}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Release.Name}}-ingress
spec: 
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{.Release.Name}}-service
          servicePort: 8080
